---
version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - USER_NAME=zookeep
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/zookeep/src
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
