---
version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - USER_NAME=appowner
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/appowner/src
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py runserver 0.0.0.0:8000
      "
    environment:
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=appuser
      - DB_PASS=secretpassword

  db:
    image: postgres:13-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secretpassword


volumes:
  app-db-data: